#!/sbin/sh
set -e

get_boot_slot() {
    getprop ro.boot.slot_suffix | sed 's/_//'
}

update_slot() {
    slot=$(/sbin/amzn_bcbtool get_active)

    if [ "$slot" = "a" ]; then
        slot_suffix="_a"
    elif [ "$slot" = "b" ]; then
        slot_suffix="_b"
    else
        echo "BCB seems broken! DO NOT REBOOT UNTIL YOU RUN 'bcbfix'."
        exit 1
    fi

    if [ "$slot" != "$(get_boot_slot)" ]; then
        resetprop ro.boot.slot_suffix "${slot_suffix}" > /dev/null 2>&1

        rm -f /dev/block/other-system /dev/block/other-boot > /dev/null 2>&1
        ln -s /dev/block/platform/mtk-msdc.0/by-name/system${slot_suffix} /dev/block/other-system > /dev/null 2>&1
        ln -s /dev/block/platform/mtk-msdc.0/by-name/boot${slot_suffix} /dev/block/other-boot > /dev/null 2>&1
    fi
}

# Run the original bcbtool, when it's done update symlinks and property.
/sbin/amzn_bcbtool $@
update_slot
